In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('./symbols.csv')

In [5]:
df[df['is_digit']]

  key     name  is_digit  is_char  is_sep
0   0  digit_0      True    False   False
1   1  digit_1      True    False   False
2   2  digit_2      True    False   False
3   3  digit_3      True    False   False
4   4  digit_4      True    False   False
5   5  digit_5      True    False   False
6   6  digit_6      True    False   False
7   7  digit_7      True    False   False
8   8  digit_8      True    False   False
9   9  digit_9      True    False   False

In [6]:
df[df['is_char']]

   key         name  is_digit  is_char  is_sep
10   a  character_a     False     True   False
11   b  character_b     False     True   False
12   c  character_c     False     True   False
13   d  character_d     False     True   False
14   e  character_e     False     True   False
15   f  character_f     False     True   False
16   g  character_g     False     True   False
17   h  character_h     False     True   False
18   i  character_i     False     True   False
19   j  character_j     False     True   False
20   k  character_k     False     True   False
21   l  character_l     False     True   False
22   m  character_m     False     True   False
23   n  character_n     False     True   False
24   o  character_o     False     True   False
25   p  character_p     False     True   False
26   q  character_q     False     True   False
27   r  character_r     False     True   False
28   s  character_s     False     True   False
29   t  character_t     False     True   False
30   u  character_u     False     True   False
31   v  character_v     False     True   False
32   w  character_w     False     True   False
33   x  character_x     False     True   False
34   y  character_y     False     True   False
35   z  character_z     False     True   False
36   A  character_A     False     True   False
37   B  character_B     False     True   False
38   C  character_C     False     True   False
39   D  character_D     False     True   False
40   E  character_E     False     True   False
41   F  character_F     False     True   False
42   G  character_G     False     True   False
43   H  character_H     False     True   False
44   I  character_I     False     True   False
45   J  character_J     False     True   False
46   K  character_K     False     True   False
47   L  character_L     False     True   False
48   M  character_M     False     True   False
49   N  character_N     False     True   False
50   O  character_O     False     True   False
51   P  character_P     False     True   False
52   Q  character_Q     False     True   False
53   R  character_R     False     True   False
54   S  character_S     False     True   False
55   T  character_T     False     True   False
56   U  character_U     False     True   False
57   V  character_V     False     True   False
58   W  character_W     False     True   False
59   X  character_X     False     True   False
60   Y  character_Y     False     True   False
61   Z  character_Z     False     True   False

In [7]:
df[df['is_sep']]

   key        name  is_digit  is_char  is_sep
62   +        plus     False    False    True
63   -       minus     False    False    True
64   *  multiplier     False    False    True
65   /     divider     False    False    True
66   (      open_p     False    False    True
67   )     close_p     False    False    True
68  \n    new_line     False    False    True
69           space     False    False    True
70   :       colon     False    False    True
71   =      equals     False    False    True
72   $         eof     False    False    True

In [9]:
for i in df.iterrows():
    print(i[1]['key'])

0
1
2
3
4
5
6
7
8
9
a
b
c
d
e
f
g
h
i
j
k
l
m
n
o
p
q
r
s
t
u
v
w
x
y
z
A
B
C
D
E
F
G
H
I
J
K
L
M
N
O
P
Q
R
S
T
U
V
W
X
Y
Z
+
-
*
/
(
)
\n

:
=
$
.

In [6]:
with open('./source_code.txt', 'r') as file:
    file_contents = file.read()
file.close()
file_contents

'procedure sum:\n5.14'

In [7]:
file_contents[14]

'\n'

In [5]:
file_contents.replace('\n', '@')

'procedure sum:@5.14'

In [3]:
for char in file_contents:
    print(char)

p
r
o
c
e
d
u
r
e

s
u
m
:


5
.
1
4